Controllers films users
thisisaleksander/java-filmorate pull request #2
Opened 2023-03-31 06:47 UTC by thisisaleksander

First version of sprint 9

2023-04-04 07:14 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа

- Все логи и текста исключений на англ язык переносим
- Доработку по классу ValidateService
- Подумать о том как сделать так чтобы при создание исключений каждый раз не писать полотно текста, тк исключения повторяются в выбрасывание это выглядит так что можно оптимизировать

Буду ждать с правками =)

2023-04-04 07:14 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>logbook-spring-boot-starter</artifactId>
Для чего эта зависимость? Она не неправильная, просто интересно

2023-04-04 07:14 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/servise/ValidateService.java
> +public class ValidateService {
Мы сделали класс бином при помощи аннотации Component а значит он живет в мире spring и поэтому крайне не рекомендуется делать в таких классах статичные методы. Поэтому тут 2 варианта:
1) убираем статику и где класс нужен используем jnject через конструктор
2) убираем аннотацию компонент

С точки зрения удобства, 1 правильнее, 2 легче, но в перспективе может чутка аукнуться

2023-04-04 07:14 UTC, krylov-sergey-sergeevich commented on test/test/servise/ValidationServiceTest.java
> +public class ValidationServiceTest {
Еще можно так:
```
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-04-04 09:01 UTC, thisisaleksander commented on test/test/servise/ValidationServiceTest.java
> +public class ValidationServiceTest {
Ага, видел в вебинаре и читал что так можно, забыл про билдеры когда писал проект

2023-04-04 09:31 UTC, thisisaleksander commented on test/test/servise/ValidationServiceTest.java
> +public class ValidationServiceTest {
В следующем спринте воспользуюсь

2023-04-04 09:41 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/servise/ValidateService.java
> +public class ValidateService {
Пока что убрал аннотацию

2023-04-05 05:02 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет!

2023-04-05 06:22 UTC, merged