Add friends likes
thisisaleksander/java-filmorate pull request #3
Opened 2023-04-08 19:04 UTC by thisisaleksander

2023-04-14 07:28 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо

- Добавить логи во все методы контроллеров
- Поправить где отписался

Буду ждать с правками =)

2023-04-14 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(InMemoryFilmStorage filmStorage, FilmService filmService) {
Давай вместо конструктора будем аннотацию из ломбока использовать requiredargsconstructor

2023-04-14 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
@Min(1)

2023-04-14 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Long> friends = new HashSet<>();
@JsonIgnore
private transient Set<Long> friendIds = new HashSet<>();

2023-04-14 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film setLike(int id, long userId) {
Может лучше addLike?

2023-04-14 07:48 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film setLike(int id, long userId) {
переименовал

2023-04-14 07:54 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@Slf4j
Все логи по идее есть в FilmServise и InMemoryFilmStorage. Добавил и в контроллеры.

2023-04-14 07:55 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(InMemoryUserStorage userStorage, UserService userService) {
Убрал конструктор и добавил аннотацию.

2023-04-14 07:58 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Set<Long> likes = new HashSet<>();
Переделал

2023-04-14 08:00 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Long> friends = new HashSet<>();
переделал

2023-04-14 08:03 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
Добавил

2023-04-14 08:03 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private String description;
Добавил, не знал что такие аннотации есть

2023-04-15 07:04 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-04-15 14:55 UTC, merged