Add database
thisisaleksander/java-filmorate pull request #4
Opened 2023-04-22 15:58 UTC by thisisaleksander

2023-04-23 17:27 UTC, thisisaleksander commented
Привет)
Думаю будет много вопросов, но я старался

2023-04-24 21:48 UTC, krylov-sergey-sergeevich requested changes
Привет, на доработку

1) Контроллер должен вернуть или объект или кинуть исключение если ситуация обязывает, никаких Optional
2) Логи сделаны для вида, давай поработаем над ними посерьезней. Особенно над теми которые в контроллерах.
3)  throws SQLException мне крайне сильно не нравится в контроллерах , это признак что что-то не так идет. Есть причины так делать аргументированные?
4) Исключения чутка с неймингом перемудрены кое где, упростить и лаконечниее сделать
5) Дубли кода - попытайся посмотреть видишь ли ты их сам и улучши код


Буду ждать с правками =)

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
Для чего?

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> addNewFilm(@RequestBody @Valid Film film) {
Контроллер должен вернуть или объект или кинуть исключение если ситуация обязывает, никаких Optional

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +public class FilmMapper implements RowMapper<Film> {
Если это бин должна быть аннотация

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private String name;
@NotBlank

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private transient Mpa mpa;
А как нибудь так нельзя просто сделать?
```

@NotNull
	private Mpa mpa;

	private LinkedHashSet<Genre> genres = new LinkedHashSet<>();
```

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new DoNotExistException(String.format(
Лучше просто UserNotFoundException(...)

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Optional<User>> getFriends(Integer id) {
List<Optional<User>> нельзя ли просто List<User> если объекта нет зачем он нам в списке

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Set<Optional<User>> getMutualFriends(Integer id, Integer otherId) {
Кидаю пример и предлагаю подумать нельзя ли полегче переписать код
```
public List<User> getCommonFriends(long userId, long otherId) {
		final String sqlQuery = "select * from USERS u, FRIENDS f, FRIENDS o " +
				"where u.USER_ID = f.FRIEND_ID AND u.USER_ID = o.FRIEND_ID AND f.USER_ID = ? AND o.USER_ID = ?";
		return jdbcTemplate.query(sqlQuery, DbUserStorage::makeUser, userId, otherId);
	}
```

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/Constants.java
> +    public static Integer STATUS_REQUEST = 1;
мжт енам ибо выглядит как енам

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/DataSourceConfig.java
> +    public DataSource getDataSource() {
А зачем так а не через конфиг

2023-04-24 21:48 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
references  - вообще не вижу

И primary key рекомендую ниже оформлять вот так - для примера:
```
create table if not exists USERS (
    user_id  integer not null primary key auto_increment,
    email    varchar(255) not null,
    login    varchar(255) not null,
    name     varchar(255),
    birthday date,
    deleted  bool default false,
    constraint USER_PK primary key (user_id)
);
```

2023-04-25 10:11 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})
При запуске выдавало ошибку: java.lang.IlligalStateException No DataSourse set

Нагуглил это решение и все заработало после того как добавил. Однако сейчас убрал и работает, странно

2023-04-25 10:12 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Optional<Film> addNewFilm(@RequestBody @Valid Film film) {
Переписал все и убрал Optional<> во всех классах

2023-04-25 10:14 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +public class FilmMapper implements RowMapper<Film> {
А почему тут нужна аннотация @Bean? При ее написании выдает ошибку и говорит что данная здесь не подходит

2023-04-25 10:16 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private String name;
Добавил

2023-04-25 10:21 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private transient Mpa mpa;
В проекте же я отдельно собираю фильм без MPA и Genre, потом добавляю эти части фильма в мапере. Получается что эти два поля не должны входить в конструктор, так как иначе эти два поля должны быть объявлены в таблице с фильмами

2023-04-25 10:22 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private transient Mpa mpa;
Можно оставить так, как сейчас?

2023-04-25 10:35 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public List<Optional<User>> getFriends(Integer id) {
Переделал

2023-04-25 10:36 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new DoNotExistException(String.format(
Создал новое исключение - NotFoundException (чтобы подходила к фильмам тоже)

2023-04-25 10:40 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/storage/DataSourceConfig.java
> +    public DataSource getDataSource() {
Через конфигурацию не получилось, вылетало в ошибку, выше писал про нее, поэтому так сделал

2023-04-25 12:48 UTC, thisisaleksander commented
Привет!

1. Контроллер возвращает объект или кидает исключение, все Optional убрал из проекта
2. Логи сделал более информативными
3. throws SQLException - убрал это исключения и переделал то откуда они появлялись
4. Исключения сделал лаконичнее
5. Убрал дубли кода где нашел, также убрал лишние части
6. Добавил референсы в таблицы

2023-04-25 21:28 UTC, thisisaleksander commented on src/main/resources/schema.sql
Добавил оформление primary key

2023-04-25 21:44 UTC, thisisaleksander commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Set<Optional<User>> getMutualFriends(Integer id, Integer otherId) {
Переписать можно, но у меня горит жесткий дедлайн и групповой проект начался вчера. Если нужно, могу переписать, а так возьму на заметку и при написании следующих запросов учту

2023-04-25 21:54 UTC, thisisaleksander commented
Поправил все о чем написал и отписался по комментариям

2023-04-26 07:17 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом все ок.

Остается момент с маппером и его логикой.
У нас должна быть структура

контроллер - сервис - бд - сервис - маппер - отдаем на фронтенд
А сейчас выходит что мы из маппера еще данные достаем есил я правильно понял, точно ли мы так хотим?

2023-04-26 07:17 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FilmMapper.java
> +public class FilmMapper implements RowMapper<Film> {
Меня крайне смущает что мы в маппере идем в бд за еще данными, почему мы их сразу достать не можем?

2023-04-26 08:19 UTC, thisisaleksander commented
Переделал FIlmMapper:
- убрал все кроме самого мадера оттуда
- вынес добавление жанров в методы где идет работа с данными

2023-04-27 05:53 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2023-04-27 17:48 UTC, merged